name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkmarx AST CLI Action
      uses: checkmarx/ast-github-action@main
      with:
        base_uri: https://ast.checkmarx.net/
        cx_tenant: via
        cx_client_id: ${{ secrets.CX_CLIENT_ID }}
        cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
